# Generated by Django 5.2.3 on 2025-10-16 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_featured',
        ),
    ]
