# Generated by Django 5.2.3 on 2025-10-16 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_productimage_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='alt_text',
        ),
    ]
