# Generated by Django 5.2.3 on 2025-11-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preview',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
