# Generated by Django 5.2.3 on 2025-11-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_attractive_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_flash_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_product_of_the_day',
            field=models.BooleanField(default=False),
        ),
    ]
