# Generated by Django 5.2.3 on 2025-07-09 17:40

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_images', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory_images', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
