# Generated by Django 5.2.3 on 2025-07-10 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_image_alter_subcategory_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
