# Generated by Django 5.2.3 on 2025-11-19 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='price',
            new_name='unit_price',
        ),
    ]
